[project]
name = "rag-practice"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.4.1",
    "langchain>=1.2.6",
    "langchain-text-splitters>=1.1.0",
]
